const chars = [
  {
    birth: "",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Adanel",
    race: "Men",
    realm: "",
    spouse: "Belemir",
  },
  {
    birth: "TA 2978",
    death: "February 26 ,3019",
    gender: "Male",
    hair: "Dark (book) Light brown (movie)",
    height: "",
    name: "Boromir",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "March ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Lagduf",
    race: "Orcs",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 280",
    death: "TA 515",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tarcil",
    race: "Men",
    realm: "Arnor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Fire-drake of Gondolin",
    race: "Dragon",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 2709",
    death: "SA 2962",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ar-Adûnakhôr",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Annael",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "FA 455",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Angrod",
    race: "Elves",
    realm: "",
    spouse: "Eldalótë",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Angrim",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 3219",
    death: "SA 3440",
    gender: "Male",
    hair: "",
    height: "",
    name: "Anárion",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 3118",
    death: "Still alive",
    gender: "Male",
    hair: "",
    height: "Tall",
    name: "Ar-Pharazôn",
    race: "Men",
    realm: "Númenor",
    spouse: "Tar-Míriel",
  },
  {
    birth: "SA 2876",
    death: "SA 3102",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ar-Sakalthôr",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 2960",
    death: "SA 3177",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ar-Gimilzôr",
    race: "Men",
    realm: "Númenor",
    spouse: "Inzilbêth",
  },
  {
    birth: "TA 2866",
    death: "TA 2977",
    gender: "Male",
    hair: "",
    height: "",
    name: "Angelimir",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Angelimar",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Angbor",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Perhaps ,Firstborn",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Nurwë",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Linda (Baggins) Proudfoot",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Bodo Proudfoot",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 510",
    gender: "Male",
    hair: "",
    height: "Tall",
    name: "Penlod",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Early ,First Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "Tallest of the Elves of Gondolin",
    name: "Pengolodh",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 654",
    death: "TA 913",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tarannon Falastur",
    race: "Men",
    realm: "Gondor",
    spouse: "Berúthiel",
  },
  {
    birth: "SA 2277",
    death: "SA 2637",
    gender: "Female",
    hair: "",
    height: "",
    name: "Tar-Vanimeldë",
    race: "Men",
    realm: "Númenor",
    spouse: "Herucalmo",
  },
  {
    birth: "SA 1320",
    death: "SA 1731",
    gender: "Female",
    hair: "",
    height: "",
    name: "Tar-Telperiën",
    race: "Men",
    realm: "Númenor",
    spouse: "None",
  },
  {
    birth: "SA 2136",
    death: "SA 2526",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Telemmaitë",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 1174",
    death: "SA 1574",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Súrion",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 3035",
    death: "SA 3255",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Palantir",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 3117",
    death: "SA 3319",
    gender: "Female",
    hair: "",
    height: "",
    name: "Tar-Míriel",
    race: "Men",
    realm: "Númenor",
    spouse: "Ar-Pharazôn",
  },
  {
    birth: "SA 1474",
    death: "SA 1873",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Minastir",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 350",
    death: "SA 751",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Elendil",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 2516",
    death: "SA 2825",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Calmacil",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 1800",
    death: "SA 2221",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Atanamir",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 543",
    death: "SA 942",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Meneldur",
    race: "Men",
    realm: "Númenor",
    spouse: "Almarian",
  },
  {
    birth: "SA 2618",
    death: "SA 2899",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Ardamin",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 1634",
    death: "SA 2035",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Ciryatan",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 1003",
    death: "SA 1404",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Anárion",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 873",
    death: "SA 1285",
    gender: "Female",
    hair: "",
    height: "",
    name: "Tar-Ancalimë",
    race: "Men",
    realm: "Númenor",
    spouse: "Hallacar",
  },
  {
    birth: "SA 1986",
    death: "SA 2386",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Ancalimon",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 192",
    death: "SA 603",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Amandil",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 2406",
    death: "SA 2737",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Alcarin",
    race: "Men",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Tanta (Hornblower) Baggins",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2922",
    death: "",
    gender: "Female",
    hair: "Dark",
    height: "Tall",
    name: "Morwen Steelsheen",
    race: "Men",
    realm: "Rohan",
    spouse: "Thengel",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Squint-eyed Southerner",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 799",
    death: "Early ,Second Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Soronto",
    race: "Men",
    realm: "",
    spouse: "None",
  },
  {
    birth: "SA 700",
    death: "SA 1098",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tar-Aldarion",
    race: "Men",
    realm: "Númenor",
    spouse: "Erendis",
  },
  {
    birth: "YT, and perhaps Firstborn",
    death: "YT 1495",
    gender: "Male",
    hair: "Black",
    height: "",
    name: "Finwë",
    race: "Elves",
    realm: "Tirion,Formenos",
    spouse: "Míriel Serindë then ,Indis",
  },
  {
    birth: "YT 1300",
    death: "FA 465",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Finrod",
    race: "Elves",
    realm: "",
    spouse: "Loved ,Amarië but they never married",
  },
  {
    birth: "YT during the ,Noontide of Valinor",
    death: "FA 472",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Fingon",
    race: "Elves",
    realm: "Hithlum",
    spouse: "",
  },
  {
    birth: "YT 1190",
    death: "FA 455",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Fingolfin",
    race: "Elves",
    realm: "Hithlum,Beleriand",
    spouse: "Anairë",
  },
  {
    birth: "TA 2950",
    death: "TA 2988",
    gender: "Female",
    hair: "Dark",
    height: "",
    name: "Finduilas of Dol Amroth",
    race: "Men",
    realm: "",
    spouse: "Denethor II",
  },
  {
    birth: "First Age",
    death: "FA 495",
    gender: "Female",
    hair: "Golden",
    height: "",
    name: "Finduilas",
    race: "Elves",
    realm: "",
    spouse: "None; betrothed to ,Gwindor, but never married.",
  },
  {
    birth: "Years of the Trees",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Findis",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Fourth Age",
    death: "sometime after ,FO 172",
    gender: "Male",
    hair: "",
    height: "",
    name: "Findegil",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT 1230",
    death: "Still Alive",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Finarfin",
    race: "Elves",
    realm: "Tirion",
    spouse: "Eärwen",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Fimbrethil",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2701",
    death: "TA 2801",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ferumbras Took II",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "Brown (film)",
    height: "",
    name: "Bill Ferny",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2870",
    death: "TA 2953",
    gender: "Male",
    hair: "",
    height: "",
    name: "Fengel",
    race: "Men",
    realm: "Rohan",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Fastred of Greenholm",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Fastred (Pelennor Fields)",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2858",
    death: "TA 2885",
    gender: "Male",
    hair: "",
    height: "",
    name: "Fastred",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "SR 1210",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Fastolph Bolger",
    race: "Hobbits",
    realm: "Shire",
    spouse: "Pansy Baggins",
  },
  {
    birth: "TA 2560",
    death: "TA 2803",
    gender: "Male",
    hair: "",
    height: "",
    name: "Farin",
    race: "Dwarves",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Mid ,Third Age",
    death: "TA 1944",
    gender: "Male",
    hair: "",
    height: "",
    name: "Faramir (son of Ondoher)",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2983",
    death: "February 26 ,82",
    gender: "Male",
    hair: "Raven",
    height: "",
    name: "Faramir",
    race: "Men",
    realm: "Minas Ithil",
    spouse: "owyn",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Falathar",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Elfstan Fairbairn",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "February 293019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Snaga (Two Towers orc)",
    race: "Orcs",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "TA 3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Snaga",
    race: "Orcs",
    realm: "",
    spouse: "",
  },
  {
    birth: "Unknown, first appeared in ,TA 2770",
    death: "November 1 ,TA 2941",
    gender: "Male",
    hair: "",
    height: "",
    name: "Smaug",
    race: "Dragons",
    realm: "Lonely Mountain",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Seers",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Robin Smallburrow",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 570",
    death: "TA 830",
    gender: "Male",
    hair: "",
    height: "",
    name: "Siriondil",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 521",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Silmariën",
    race: "Men",
    realm: "",
    spouse: "Elatan",
  },
  {
    birth: "Unknown, possibly during the ,First Age",
    death: "Unknown, possibly TA 3019",
    gender: "Female",
    hair: "",
    height: "Large and immense",
    name: "Shelob",
    race: "Great Spiders",
    realm: "Torech Ungol",
    spouse: "",
  },
  {
    birth: "TA 2050",
    death: "",
    gender: "Male",
    hair: "",
    height: "7'1",
    name: "Shagrat",
    race: "Black Uruk",
    realm: "Cirith Ungol",
    spouse: "",
  },
  {
    birth: "",
    death: "TA 2000",
    gender: "Male",
    hair: "None",
    height: "",
    name: "Scatha",
    race: "Dragons",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "March 25 ,3019",
    gender: "Male",
    hair: "Various ",
    height: "Various until ",
    name: "Sauron",
    race: "Maiar",
    realm: "",
    spouse: "None",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "3 November ,3019",
    gender: "Male",
    hair: "White",
    height: "",
    name: "Saruman",
    race: "Maiar",
    realm: "Isengard,Nan Curunír",
    spouse: "None",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Saradoc Brandybuck",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "",
    name: "Salmar",
    race: "Ainur",
    realm: "",
    spouse: "",
  },
  {
    birth: "SR 1308",
    death: "SR 1407",
    gender: "Male",
    hair: "",
    height: "",
    name: "Saradas Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "Mid-,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Sangahyando",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2920",
    death: "FO 50",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ted Sandyman",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Sandyman",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "Fate officially unknown",
    gender: "Male",
    hair: "",
    height: "Short",
    name: "Salgant",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Sagroth",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "FA 484",
    gender: "Male",
    hair: "",
    height: "",
    name: "Saeros",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Fourth Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Saelon",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "about ,FA 430",
    death: "FA 495",
    gender: "Male",
    hair: "",
    height: "",
    name: "Sador",
    race: "Men",
    realm: "",
    spouse: "None known",
  },
  {
    birth: "SR 1179",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Sadoc Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2964",
    death: "TA 3019",
    gender: "Male",
    hair: "Sandy",
    height: "1.22m (4'0\")",
    name: "Lotho Sackville-Baggins",
    race: "Hobbits",
    realm: "",
    spouse: "None",
  },
  {
    birth: "TA 2918",
    death: "TA 3020",
    gender: "Female",
    hair: "",
    height: "1.17m (3'10\")",
    name: "Lobelia Sackville-Baggins",
    race: "Hobbit",
    realm: "",
    spouse: "Otho Sackville-Baggins",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Camellia (Sackville) Baggins",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 1126",
    death: "TA 1366",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rómendacil II",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "YT",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rúmil (Noldo)",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 310",
    death: "TA 541",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rómendacil I",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "c. T.A. 2328",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Rían (Gondor)",
    race: "Men",
    realm: "",
    spouse: "Unnamed husband",
  },
  {
    birth: "FA 450",
    death: "FA 473",
    gender: "Female",
    hair: "",
    height: "",
    name: "Rían",
    race: "Men",
    realm: "",
    spouse: "Huor",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rufus Burrows",
    race: "Hobbit",
    realm: "",
    spouse: "Asphodel Brandybuck",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Ruffian Leader",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rúmil of Lórien",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Rudolph Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "SR 1255",
    death: "SR 1348",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rudigar Bolger",
    race: "Hobbits",
    realm: "Bree",
    spouse: "Belba Baggins",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Ruby Gamgee",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2788",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Roäc",
    race: "Raven",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2849",
    death: "Late ,Third Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rowan Greenhand",
    race: "Hobbits",
    realm: "Shire",
    spouse: "Belba Baggins",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Andwise Roper",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 510",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rog",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "River-woman",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Mid ,First Age",
    death: "FA 460",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ragnor",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "Late First Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ragnir",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "FA 460",
    gender: "Male",
    hair: "",
    height: "",
    name: "Radhruin",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Radbug",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "None",
    gender: "Male",
    hair: "Brown-gray (films)",
    height: "",
    name: "Radagast",
    race: "Maiar",
    realm: "",
    spouse: "None",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Olo Proudfoot",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Sancho Proudfoot",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2904",
    death: "TA 3005",
    gender: "Male",
    hair: "Brown Gray (movie)",
    height: "",
    name: "Odo Proudfoot",
    race: "Hobbits",
    realm: "",
    spouse: "Mrs. Proudfoot",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Mrs. Proudfoot",
    race: "Hobbits",
    realm: "",
    spouse: "Odo Proudfoot",
  },
  {
    birth: "",
    death: "FA 486",
    gender: "Male",
    hair: "",
    height: "",
    name: "Khîm",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Second Age",
    death: "",
    gender: "Male",
    hair: "White",
    height: "",
    name: "Khamûl",
    race: "Men,Wraith",
    realm: "Rhûn,Dol Guldur,Sauron",
    spouse: "",
  },
  {
    birth: "TA 2947",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Ivriniel",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2857",
    death: "TA 2929",
    gender: "Female",
    hair: "Brown (film)",
    height: "",
    name: "Ivorwen",
    race: "Men",
    realm: "",
    spouse: "Dírhael",
  },
  {
    birth: "SA 532",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Isilmë",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "After ,SA 1320",
    death: "Before ,SA 1731",
    gender: "Male",
    hair: "",
    height: "",
    name: "Isilmo",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 3209",
    death: "TA 2",
    gender: "Male",
    hair: "Black",
    height: "Very tall almost 7'1",
    name: "Isildur",
    race: "Men",
    realm: "Arnor,Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2832",
    death: "TA 2930",
    gender: "Male",
    hair: "",
    height: "",
    name: "Isengrim Took III",
    race: "Hobbits",
    realm: "",
    spouse: "Not married",
  },
  {
    birth: "TA 2842",
    death: "TA 2946",
    gender: "Male",
    hair: "",
    height: "",
    name: "Isembold Took",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife ",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "",
    name: "Irmo",
    race: "Ainur",
    realm: "",
    spouse: "Estë",
  },
  {
    birth: "b. ,TA 2990",
    death: "Early-,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Iorlas",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Ioreth",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Second Age",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Inzilbêth",
    race: "Men",
    realm: "",
    spouse: "Ar-Gimilzôr",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Inigo Baggins",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "Unknown, probably still alive",
    gender: "Male",
    hair: "Probably Golden",
    height: "",
    name: "Ingwion",
    race: "Elf",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT, and perhaps firstborn",
    death: "Still Alive",
    gender: "Male",
    hair: "Probably Golden",
    height: "Tall",
    name: "Ingwë",
    race: "Elves",
    realm: "Valinor,Taniquetil",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ingold",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Mid ,First Age",
    death: "FA 495",
    gender: "Male",
    hair: "",
    height: "",
    name: "Indor",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "Still Alive",
    gender: "Female",
    hair: "Golden",
    height: "Tall",
    name: "Indis",
    race: "Elves",
    realm: "Tirion",
    spouse: "Finwë",
  },
  {
    birth: "TA 1950",
    death: "TA 2076",
    gender: "Male",
    hair: "",
    height: "",
    name: "Imrazôr",
    race: "Men",
    realm: "",
    spouse: "Mithrellas",
  },
  {
    birth: "TA 2955",
    death: "FO 34",
    gender: "Male",
    hair: "Black",
    height: "Tall",
    name: "Imrahil",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "around FA 325",
    death: "First Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Imlach",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Unknown, Awakened in the ,Years of the Trees",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Iminyë",
    race: "Elves",
    realm: "",
    spouse: "Imin",
  },
  {
    birth: "Unknown, Awakened in the ,Years of the Trees",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Imin",
    race: "Elves",
    realm: "",
    spouse: "Iminyë",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "Varies, White ",
    height: "Varies",
    name: "Eru Ilúvatar",
    race: "God",
    realm: "Timeless Halls",
    spouse: "None",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Ilmarë",
    race: "Ainur",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT 1469",
    death: "Still Alive",
    gender: "Female",
    hair: "Golden",
    height: "Tall",
    name: "Idril",
    race: "Elves",
    realm: "",
    spouse: "Tuor",
  },
  {
    birth: "",
    death: "FA 489",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ibûn",
    race: "Dwarves",
    realm: "",
    spouse: "Unknown, possibly none",
  },
  {
    birth: "Mid-,Third Age",
    death: "Mid-,Third Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Húrin of Emyn Arnen",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2515",
    death: "TA 2628",
    gender: "Male",
    hair: "",
    height: "",
    name: "Húrin II",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2124",
    death: "TA 2244",
    gender: "Male",
    hair: "",
    height: "",
    name: "Húrin I",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "FA 441",
    death: "FA 502",
    gender: "Male",
    hair: "Golden, grey (in old age)",
    height: "",
    name: "Húrin",
    race: "Men",
    realm: "",
    spouse: "Morwen Eledhwen",
  },
  {
    birth: "Late ,Third Age",
    death: "Winter of ,TA 2759",
    gender: "Male",
    hair: "",
    height: "",
    name: "Háma (Helm's son)",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2975",
    death: "March 3, or ,4 ,3019",
    gender: "Male",
    hair: "Reddish brown (movie)",
    height: "",
    name: "Háma",
    race: "Men",
    realm: "",
    spouse: "Unknown, possibly none",
  },
  {
    birth: "TA 1391",
    death: "TA 1621",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hyarmendacil II",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 899",
    death: "TA 1149",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hyarmendacil I",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Hurin (Warden of the Keys)",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 442",
    death: "FA 473",
    gender: "Male",
    hair: "Golden",
    height: "Tallest of all mortal men save his son Tuor only",
    name: "Huor",
    race: "Men",
    realm: "",
    spouse: "Rían",
  },
  {
    birth: "Late ,FA",
    death: "FA 499",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hunthor",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,First Age",
    death: "FA 473",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hundar",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Mid ,FA",
    death: "Mid FA ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hundad",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "First Age",
    death: "FA 466",
    gender: "Male",
    hair: "",
    height: "Horse-sized",
    name: "Huan",
    race: "Wolfhound",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Tobold Hornblower",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "Late ,TA 3018",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tobias Hornblower",
    race: "Hobbits",
    realm: "Shire",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Tanta Hornblower",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Possibly late ,Third Age",
    death: "March 15 ,TA 3019",
    gender: "Male",
    hair: "Blond (Video game)",
    height: "",
    name: "Horn",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eönwë",
    race: "Ainur",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "FA 400",
    gender: "Male",
    hair: "Dark",
    height: "Tall",
    name: "Eöl",
    race: "Elves",
    realm: "Nan Elmoth",
    spouse: "Aredhel",
  },
  {
    birth: "Years of the Trees",
    death: "Still alive",
    gender: "Female",
    hair: "Star-like ",
    height: "",
    name: "Eärwen",
    race: "Elves",
    realm: "",
    spouse: "Finarfin",
  },
  {
    birth: "TA 1928",
    death: "TA 2050",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärnur",
    race: "Men",
    realm: "Gondor",
    spouse: "None",
  },
  {
    birth: "TA 1883",
    death: "TA 2043",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärnil II",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 736",
    death: "TA 936",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärnil I",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 361",
    death: "Early ,Second Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärendur of Númenor",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 640",
    death: "TA 861",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärendur of Arnor",
    race: "",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Second Age",
    death: "Late Second Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärendur (Lord of Andúnië)",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 48",
    death: "TA 324",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eärendil of Gondor",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "FA 503",
    death: "Still Alive",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Eärendil",
    race: "Half-elven",
    realm: "",
    spouse: "Elwing",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Female",
    hair: "",
    height: "",
    name: "Estë",
    race: "Ainur",
    realm: "",
    spouse: "Irmo",
  },
  {
    birth: "Late ,Second Age",
    death: "Early ,Third Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Estelmo",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "Tall",
    name: "Erkenbrand",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Erestor",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 771",
    death: "SA 985",
    gender: "Female",
    hair: "Dark",
    height: "",
    name: "Erendis",
    race: "Men",
    realm: "Númenor",
    spouse: "Tar-Aldarion",
  },
  {
    birth: "unknown",
    death: "unknown",
    gender: "Male",
    hair: "",
    height: "",
    name: "Erellont",
    race: "Elves",
    realm: "",
    spouse: "unknown",
  },
  {
    birth: "TA 2990",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Erchirion",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 1999",
    death: "TA 2116",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eradan",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2995",
    death: "FO",
    gender: "Female",
    hair: "Pale gold",
    height: "Tall",
    name: "owyn",
    race: "Men",
    realm: "",
    spouse: "Faramir",
  },
  {
    birth: "TA 2485",
    death: "TA 2545",
    gender: "Male",
    hair: "Blond",
    height: "",
    name: "Eorl the Young",
    race: "Men",
    realm: "Rohan",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2990",
    death: "FO 63",
    gender: "Male",
    hair: "Dirty blond",
    height: "Tall-6'6",
    name: "omer",
    race: "Men",
    realm: "Rohan",
    spouse: "Lothíriel after the War of the Ring",
  },
  {
    birth: "Unknown, possibly in the ,First Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Enerdhil",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Unknown, Awakened in the ,Years of the Trees",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Enelyë",
    race: "Elves",
    realm: "",
    spouse: "Enel",
  },
  {
    birth: "Unknown, Awakened in the Years of the Trees",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Enel",
    race: "Elves",
    realm: "",
    spouse: "Enelyë",
  },
  {
    birth: "FA 406",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Emeldir",
    race: "Men",
    realm: "",
    spouse: "Barahir",
  },
  {
    birth: "FA 503",
    death: "Still Alive",
    gender: "Female",
    hair: "Dark",
    height: "",
    name: "Elwing",
    race: "Half-elven",
    realm: "",
    spouse: "Eärendil",
  },
  {
    birth: "FA 500",
    death: "FA 506",
    gender: "Male",
    hair: "Possibly dark",
    height: "",
    name: "Eluréd and Elurín",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 532",
    death: "SA 442",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elros",
    race: "Half-elven",
    realm: "Númenor",
    spouse: "Unnamed wife",
  },
  {
    birth: "FA 532",
    death: "Still alive; departed to ,Aman, on ,September 29 ,3021",
    gender: "Male",
    hair: "Dark",
    height: "Tall",
    name: "Elrond",
    race: "Half-elven",
    realm: "Rivendell",
    spouse: "Celebrían",
  },
  {
    birth: "TA 2987",
    death: "FO 57",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elphir",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Elmo",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 130",
    death: "",
    gender: "Male",
    hair: "Dark",
    height: "Tall",
    name: "Elladan and Elrohir",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "FO 8",
    death: "FO 103",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elfwine",
    race: "Men",
    realm: "Rohan",
    spouse: "",
  },
  {
    birth: "TA 2950",
    death: "TA 2978",
    gender: "Female",
    hair: "",
    height: "",
    name: "Elfhild",
    race: "Men",
    realm: "Rohan",
    spouse: "Théoden",
  },
  {
    birth: "TA 2985",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Elfhelm",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "YT 1500",
    gender: "Female",
    hair: "Golden",
    height: "Tall",
    name: "Elenwë",
    race: "Elves",
    realm: "",
    spouse: "Turgon",
  },
  {
    birth: "TA 552",
    death: "TA 777",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elendur of Arnor",
    race: "Men",
    realm: "Arnor",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 3299",
    death: "TA 2",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elendur",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 3119",
    death: "SA 3441 ",
    gender: "Male",
    hair: "Brown",
    height: "7' 10",
    name: "Elendil",
    race: "Men",
    realm: "Arnor,Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "Presumably still alive",
    gender: "",
    hair: "",
    height: "",
    name: "Elemmírë (elf)",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 510,(presumably)",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elemmakil",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "FO 43",
    death: "Before ,FO 220",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Eldarion",
    race: "Men",
    realm: "Reunited Kingdom,Arnor,Gondor",
    spouse: "",
  },
  {
    birth: "YT",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Eldalótë",
    race: "Elves",
    realm: "",
    spouse: "Angrod",
  },
  {
    birth: "TA 1255",
    death: "TA 1490",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eldacar (King of Gondor)",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 87",
    death: "TA 339",
    gender: "Male",
    hair: "",
    height: "",
    name: "Eldacar (King of Arnor)",
    race: "Men",
    realm: "Arnor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elboron",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Early ,Second Age",
    death: "Early Second Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Elatan",
    race: "Men",
    realm: "",
    spouse: "Silmariën",
  },
  {
    birth: "Mid ,First Age",
    death: "Between ,FA 455, - ,FA 460",
    gender: "Female",
    hair: "",
    height: "",
    name: "Eilinel",
    race: "Men",
    realm: "",
    spouse: "Gorlim",
  },
  {
    birth: "Late ,Third Age",
    death: "Late Third Age",
    gender: "Female",
    hair: "",
    height: "",
    name: "Eglantine (Banks) Took",
    race: "Hobbits",
    realm: "",
    spouse: "Paladin Took II",
  },
  {
    birth: "",
    death: "FA 538",
    gender: "Male",
    hair: "",
    height: "",
    name: "Egalmoth (elf)",
    race: "Elves",
    realm: "",
    spouse: "Unknown, possibly none",
  },
  {
    birth: "TA 2626",
    death: "TA 2743",
    gender: "Male",
    hair: "",
    height: "",
    name: "Egalmoth",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "FA 465",
    gender: "Male",
    hair: "",
    height: "",
    name: "Edrahil",
    race: "Elf",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 510",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Ecthelion of the Fountain",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2886",
    death: "TA 2984",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ecthelion II",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2600",
    death: "TA 2698",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ecthelion I",
    race: "Men",
    realm: "",
    spouse: "Possibly none",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Ebor",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dúnhere",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2760",
    death: "After ,TA 2941",
    gender: "Female",
    hair: "",
    height: "",
    name: "Dís",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "Late First Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dírhavel",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2838",
    death: "After ,TA 2929",
    gender: "Male",
    hair: "Brown (film)",
    height: "",
    name: "Dírhael",
    race: "Men",
    realm: "",
    spouse: "Ivorwen",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Déorwine",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2644",
    death: "TA 2718",
    gender: "Male",
    hair: "",
    height: "",
    name: "Déor",
    race: "Men,Rohirrim",
    realm: "Rohan",
    spouse: "",
  },
  {
    birth: "Between TA 2400 and ,TA 2430",
    death: "TA 2463",
    gender: "Male",
    hair: "Dark-brown",
    height: "",
    name: "Déagol",
    race: "Hobbits",
    realm: "",
    spouse: "None",
  },
  {
    birth: "TA 3011",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Borlas",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,First Age",
    death: "FA 473",
    gender: "Male",
    hair: "",
    height: "",
    name: "Borlad",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 1879",
    death: "TA 1998",
    gender: "Male",
    hair: "",
    height: "",
    name: "Pelendur",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of Arda",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Pallando",
    race: "Ainur",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2910",
    death: "TA 3012",
    gender: "Male",
    hair: "",
    height: "1.22m (4'0\")",
    name: "Otho Sackville-Baggins",
    race: "Hobbits",
    realm: "",
    spouse: "Lobelia Sackville-Baggins",
  },
  {
    birth: "TA 222",
    death: "TA 492",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ostoher",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "Before the creation ,Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ossë",
    race: "Ainur",
    realm: "",
    spouse: "Uinen",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Orophin",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "First Age",
    death: "SA 3434",
    gender: "Male",
    hair: "",
    height: "",
    name: "Oropher",
    race: "Elves",
    realm: "Woodland Realm",
    spouse: "Unnamed wife",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "Varies",
    name: "Oromë",
    race: "Ainur",
    realm: "",
    spouse: "Vána",
  },
  {
    birth: "SA 382",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Oromendil",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2576",
    death: "TA 2685",
    gender: "Male",
    hair: "",
    height: "",
    name: "Orodreth (Steward)",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "YT",
    death: "FA 495 ,Battle of Tumhalad",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Orodreth",
    race: "Elves",
    realm: "Nargothrond",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Orleg",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2865",
    death: "TA 2994",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ori",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 510",
    gender: "Male",
    hair: "",
    height: "",
    name: "Orcobal",
    race: "Orcs",
    realm: "",
    spouse: "",
  },
  {
    birth: "Sometime before ,SA 799",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Orchaldor",
    race: "Men",
    realm: "",
    spouse: "Ailinel",
  },
  {
    birth: "TA 1787",
    death: "TA 1944",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ondoher",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "Possibly Firstborn",
    death: "Still Alive",
    gender: "Male",
    hair: "Silver",
    height: "",
    name: "Olwë",
    race: "Elves",
    realm: "Tol Eressëa,Alqualondë",
    spouse: "Unnamed Wife",
  },
  {
    birth: "TA 2923",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Old Noakes",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Old Man Willow",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Second Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Ohtar",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Early ,Second Age",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Núneth",
    race: "Men",
    realm: "",
    spouse: "Beregar",
  },
  {
    birth: "Late Second Age ",
    death: "SA 3065",
    gender: "Male",
    hair: "",
    height: "",
    name: "Númendil",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "Late Third Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Nár",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "TA 2994",
    gender: "Male",
    hair: "",
    height: "",
    name: "Náli",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2338",
    death: "TA 2585",
    gender: "Male",
    hair: "",
    height: "",
    name: "Náin II",
    race: "Dwarves",
    realm: "Grey Mountains",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 1832",
    death: "TA 1981",
    gender: "Male",
    hair: "",
    height: "",
    name: "Náin I",
    race: "Dwarves",
    realm: "Khazad-dûm",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2665",
    death: "TA 2799",
    gender: "Male",
    hair: "",
    height: "",
    name: "Náin (father of Dáin II Ironfoot)",
    race: "Dwarves",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hob Hayward",
    race: "Hobbits",
    realm: "Shire",
    spouse: "",
  },
  {
    birth: "TA 2846",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hob Gammidge",
    race: "Hobbit",
    realm: "",
    spouse: "Rowan",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "Tall",
    name: "Hirluin",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Hild",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "TA 3019",
    gender: "Male",
    hair: "",
    height: "Tall",
    name: "Hirgon",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "FO 41",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Herumor (Fourth Age)",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Second Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Herumor",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 2286",
    death: "SA 2657",
    gender: "Male",
    hair: "",
    height: "",
    name: "Herucalmo",
    race: "Men",
    realm: "",
    spouse: "Tar-Vanimeldë",
  },
  {
    birth: "Late-,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Herubrand",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2037",
    death: "TA 2148",
    gender: "Male",
    hair: "",
    height: "",
    name: "Herion",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hendor",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late-,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "Gray",
    height: "",
    name: "Herefara",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Early ,Second Age",
    death: "unknown",
    gender: "Male",
    hair: "",
    height: "",
    name: "Henderch",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2691",
    death: "TA 2759",
    gender: "Male",
    hair: "",
    height: "",
    name: "Helm Hammerhand",
    race: "Men",
    realm: "Rohan",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Mat Heathertoes",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Sometime before ,SA 799",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hatholdir",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "F.A. 365",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hathol",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Mid ,First Age",
    death: "FA 460",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hathaldir",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 419",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Hareth",
    race: "Men",
    realm: "",
    spouse: "Galdor",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Harding",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 470",
    death: "FA 501",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hardang",
    race: "Men",
    realm: "",
    spouse: "None",
  },
  {
    birth: "FA 441",
    death: "FA 495",
    gender: "",
    hair: "",
    height: "",
    name: "Handir",
    race: "Men",
    realm: "Brethil",
    spouse: "Beldis",
  },
  {
    birth: "TA 2760",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hamfast of Gamwich",
    race: "Hobbit",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,First Age",
    death: "Late First Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Halmir",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 711",
    death: "Mid ,Second Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hallatan",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2480",
    death: "TA 2605",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hallas (Steward)",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "SA 852",
    death: "SA 1211",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hallacar",
    race: "Men",
    realm: "",
    spouse: "Tar-Ancalimë",
  },
  {
    birth: "Late ,Third Age",
    death: "Winter of ,TA 2758",
    gender: "Male",
    hair: "",
    height: "",
    name: "Haleth (Helm's son)",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 341",
    death: "FA 420",
    gender: "Female",
    hair: "",
    height: "",
    name: "Haleth",
    race: "Men",
    realm: "",
    spouse: "None",
  },
  {
    birth: "",
    death: "TA 3019",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Haldir (Lorien)",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 413",
    death: "FA 473",
    gender: "Male",
    hair: "",
    height: "",
    name: "Haldir (Haladin)",
    race: "Men",
    realm: "",
    spouse: "Glóredhel",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Haldar",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Haldad",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2916",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "Black",
    height: "Tall",
    name: "Halbarad",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 390",
    death: "FA 455",
    gender: "Male",
    hair: "Golden",
    height: "",
    name: "Hador",
    race: "Men",
    realm: "",
    spouse: "Gildis",
  },
  {
    birth: "Late-,Third Age",
    death: "February 28 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gárulf",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2245",
    death: "TA 2395",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hador (Steward)",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2767",
    death: "March 17 ,3019",
    gender: "Male",
    hair: "",
    height: "4'5 - 5' (Estimate) ",
    name: "Dáin II Ironfoot",
    race: "Dwarves",
    realm: "Lonely Mountain",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2440",
    death: "TA 2589",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dáin I",
    race: "Dwarves",
    realm: "Grey Mountains",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2772",
    death: "FO 91",
    gender: "Male",
    hair: "Brown",
    height: "",
    name: "Dwalin",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "January 253019",
    gender: "Male",
    hair: "Mane of red flames",
    height: "Slightly larger and taller than a Man (book), 20 feet (movie)",
    name: "Durin's Bane",
    race: "Maiar,Balrog",
    realm: "",
    spouse: "",
  },
  {
    birth: "FO 2",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Durin VII",
    race: "Dwarves",
    realm: "Khazad-dum",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Durin",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late-,Third Age",
    death: "Early-,Fourth Age",
    gender: "Male",
    hair: "Dark (Decipher Card)",
    height: "Tall",
    name: "Duinhir",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "TA 3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Duilin",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 465",
    gender: "Male",
    hair: "",
    height: "",
    name: "Draugluin",
    race: "Werewolves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "FA 499",
    gender: "Males",
    hair: "",
    height: "",
    name: "Dorlas",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2827",
    death: "",
    gender: "Male",
    hair: "Gray (film)",
    height: "",
    name: "Dori",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dodinas Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2328",
    death: "TA 2435",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dior (Steward)",
    race: "Men",
    realm: "",
    spouse: "Possibly none",
  },
  {
    birth: "FA 470, ",
    death: "FA 506, ",
    gender: "Male",
    hair: "Possibly dark",
    height: "",
    name: "Dior",
    race: "Half-elven",
    realm: "Doriath",
    spouse: "Nimloth",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Dina Diggle",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "SR 1316",
    death: "SR 1410",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dinodas Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2995",
    death: "Before ,FO 63",
    gender: "Female",
    hair: "Brown (film)",
    height: "",
    name: "Diamond Took",
    race: "Hobbits",
    realm: "",
    spouse: "Peregrin Took",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dervorin",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "Mid ,March ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Derufin",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2930",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "Dark, grey (in old age)",
    height: "",
    name: "Denethor II",
    race: "Men",
    realm: "",
    spouse: "Finduilas",
  },
  {
    birth: "TA 2375",
    death: "TA 2477",
    gender: "Male",
    hair: "",
    height: "",
    name: "Denethor I",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "YT",
    death: "YT 1497",
    gender: "Male",
    hair: "",
    height: "",
    name: "Denethor (First Age)",
    race: "Elves",
    realm: "Ossiriand",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "TA 3019",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Damrod",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Daisy Gamgee",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "FA 460",
    gender: "Male",
    hair: "",
    height: "",
    name: "Dairuin",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "",
    gender: "Male",
    hair: "Dark ",
    height: "",
    name: "Daeron",
    race: "Elves",
    realm: "",
    spouse: "None",
  },
  {
    birth:
      "YT, 1050. Age = 11,484.9 Sun Years or 1,198.6 Valian Years as of FO 121 (death of Arwen).",
    death:
      "Still alive, sailed into the ,West, sometime during the ,Fourth Age last of all elves to leave ,Middle-earth,.",
    gender: "Male",
    hair: "Silver, bearded",
    height: "Very tall",
    name: "Círdan",
    race: "Elves",
    realm: "",
    spouse: "Presumably none",
  },
  {
    birth: "During the ,Noontide of Valinor",
    death: "FA 506",
    gender: "Male",
    hair: "Dark",
    height: "",
    name: "Curufin",
    race: "Elves",
    realm: "Himlad",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2238",
    death: "TA 2488",
    gender: "Male",
    hair: "",
    height: "",
    name: "in (King of Durin's Folk)",
    race: "Men",
    realm: "Grey Mountains",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2774",
    death: "TA 2994",
    gender: "Male",
    hair: "",
    height: "",
    name: "in",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "Various",
    name: "mar",
    race: "Ainur",
    realm: "",
    spouse: "None",
  },
  {
    birth: "Early ,First Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "bal",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "rimë",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 700",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "rildë",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "othain",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2961",
    death: "TA 3002",
    gender: "Male",
    hair: "Blond",
    height: "",
    name: "omund",
    race: "Men",
    realm: "",
    spouse: "Théodwyn",
  },
  {
    birth: "c. ,TA 2544",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "ofor",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Early ,Second Age",
    death: "Early Second Age ",
    gender: "Female",
    hair: "White or grey",
    height: "",
    name: "Zamîn",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 371",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Yávien",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Female",
    hair: "",
    height: "Varies",
    name: "Yavanna",
    race: "Ainur",
    realm: "Pastures of Yavanna",
    spouse: "Aulë",
  },
  {
    birth: "Late-,Third Age",
    death: "Early-,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Wídfara",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "TA 2759",
    gender: "Male",
    hair: "",
    height: "",
    name: "Wulf I",
    race: "Men",
    realm: "Rohan",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "FA 473",
    gender: "Male",
    hair: "",
    height: "",
    name: "Borlach",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2450",
    death: "TA 2711",
    gender: "Male",
    hair: "",
    height: "",
    name: "Borin",
    race: "Dwarven",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2834",
    death: "",
    gender: "Male",
    hair: "Ginger",
    height: "",
    name: "Bombur",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Unknown, before the coming of Melkor",
    death: "Unknown, possibly immortal",
    gender: "Male",
    hair: "Brown",
    height: "",
    name: "Tom Bombadil",
    race: "",
    realm: "Old Forest",
    spouse: "Goldberry",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Wilimar Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2904",
    death: "TA 3000",
    gender: "Male",
    hair: "",
    height: "",
    name: "Wilibald Bolger",
    race: "Hobbits",
    realm: "",
    spouse: "Prisca Baggins",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Theobald Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Rudibert Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2938",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Rosamunda (Took) Bolger",
    race: "Men",
    realm: "",
    spouse: "Odovacar Bolger",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Prisca (Baggins) Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2935",
    death: "FO 10",
    gender: "Male",
    hair: "",
    height: "",
    name: "Odovacar Bolger",
    race: "Hobbits",
    realm: "",
    spouse: "Rosamunda Took",
  },
  {
    birth: "TA 2897",
    death: "Late ,Third Age",
    gender: "Female",
    hair: "",
    height: "",
    name: "Jessamine (Boffin) Bolger",
    race: "Hobbits",
    realm: "",
    spouse: "Herugar Bolger",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Gundahar Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2980",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Fredegar Bolger",
    race: "Hobbits",
    realm: "",
    spouse: "unknown, possibly unmarried",
  },
  {
    birth: "TA 2942",
    death: "FO 22",
    gender: "Male",
    hair: "Brown (movie)",
    height: "",
    name: "Filibert Bolger",
    race: "Hobbits",
    realm: "",
    spouse: "Poppy Chubb-Baggins",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Adalgar Bolger",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "TA 2941",
    gender: "Male",
    hair: "None",
    height: "8,4  Body weight = 190kg",
    name: "Bolg",
    race: "Goblin,Orc",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Boldog (Character)",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2843",
    death: "",
    gender: "Male",
    hair: "Dark Brown (films)",
    height: "",
    name: "Bofur",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Uffo Boffin",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2988",
    death: "Early-,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Tosto Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2860",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Rollo Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Lavender Grubb",
  },
  {
    birth: "TA 2812",
    death: "TA 2900",
    gender: "Male",
    hair: "",
    height: "",
    name: "Otto Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Lavender Grubb",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Lavender (Grubb) Boffin",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2894",
    death: "TA 2986",
    gender: "Male",
    hair: "",
    height: "",
    name: "Jago Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "Late Third Age ",
    gender: "Female",
    hair: "",
    height: "",
    name: "Ivy (Goodenough) Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Buffo Boffin",
  },
  {
    birth: "TA 2854",
    death: "TA 2945",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hugo Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Donnamira Took",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Gruffo Boffin",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2946",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Griffo Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Daisy Baggins",
  },
  {
    birth: "TA 2904",
    death: "TA 3004",
    gender: "Female",
    hair: "",
    height: "",
    name: "Gerda (Boffin) Bolger",
    race: "Hobbits",
    realm: "",
    spouse: "Adalbert Bolger",
  },
  {
    birth: "TA 2978",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Folco Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "before ,TA 2860",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Druda Burrows Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Rollo Boffin",
  },
  {
    birth: "TA 2950",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Daisy (Baggins) Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Griffo Boffin",
  },
  {
    birth: "Late ,Third Age",
    death: "Late ,Third Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Buffo Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Ivy Goodenough",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Briffo Boffin",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2767",
    death: "TA 2858",
    gender: "Male",
    hair: "",
    height: "",
    name: "Bosco Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2769",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Basso Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "None",
  },
  {
    birth: "TA 2856",
    death: "TA 2948",
    gender: "Female",
    hair: "",
    height: "",
    name: "Donnamira (Took) Boffin",
    race: "Hobbits",
    realm: "",
    spouse: "Hugo Boffin",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Bodruith",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "Early ,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Bob",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 1560",
    death: "Sometime after ,TA 1601",
    gender: "Male",
    hair: "",
    height: "",
    name: "Blanco",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "Late Third Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Bladorthin",
    race: "Men",
    realm: "Lake-town,Dale,Rhûn,Dorwinion",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Black Serpent",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Bilbo Gardner",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "22 September ,TA 2890",
    death: "Unknown (Last sighting 29 SeptemberTA 3021,) (,SR 1421,)",
    gender: "Male",
    hair: "Brown, later white",
    height: "1.25m (4'1\")",
    name: "Bilbo Baggins",
    race: "Hobbits",
    realm: "",
    spouse: "None",
  },
  {
    birth: "TA 2814",
    death: "UnknownFourth Age",
    gender: "Male",
    hair: "Black/ Grey (film)",
    height: "4'5\" (film)",
    name: "Bifur",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Early  ,Third Age",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Berúthiel",
    race: "Men",
    realm: "Gondor",
    spouse: "Tarannon Falastur",
  },
  {
    birth: "TA 3009",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Bergil",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2655",
    death: "TA 2763",
    gender: "Male",
    hair: "",
    height: "",
    name: "Beren (Steward)",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "FA 432",
    death: "FA 466",
    gender: "Male",
    hair: "Dark",
    height: "Tall",
    name: "Beren",
    race: "Men",
    realm: "",
    spouse: "Lúthien Tinúviel",
  },
  {
    birth: "Early ,Fourth Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Berelach",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Mid ,First Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Beren (Belemir's son)",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2837",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Nori",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 222",
    death: "Early ,Second Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Nolondil",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Nob",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 473",
    death: "FA 499",
    gender: "Female",
    hair: "Golden",
    height: "Tall",
    name: "Niënor",
    race: "Men",
    realm: "",
    spouse: "Túrin Turambar",
  },
  {
    birth: "SR 1261",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Nina Lightfoot",
    race: "Hobbits",
    realm: "Shire",
    spouse: "Theobald Bolger",
  },
  {
    birth: "YT",
    death: "TA 1981",
    gender: "Female",
    hair: "Possibly golden",
    height: "",
    name: "Nimrodel",
    race: "Elves",
    realm: "",
    spouse: "Loved ,Amroth",
  },
  {
    birth: "Unknown, possibly sometime during the ,Years of the Trees",
    death: "FA 506",
    gender: "Female",
    hair: "",
    height: "",
    name: "Nimloth (elf)",
    race: "Elves",
    realm: "Doriath",
    spouse: "Dior Eluchíl",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Female",
    hair: "",
    height: "",
    name: "Nienna",
    race: "Ainur",
    realm: "Valinor,Halls of Nienna",
    spouse: "None",
  },
  {
    birth: "unknown",
    death: "Immortal",
    gender: "Female",
    hair: "",
    height: "Various",
    name: "Nielíqui",
    race: "Ainur",
    realm: "",
    spouse: "None",
  },
  {
    birth: "SA 840",
    death: "Mid ,Second Age",
    gender: "Female",
    hair: "",
    height: "",
    name: "Nessanië",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Female",
    hair: "",
    height: "Varies",
    name: "Nessa",
    race: "Ainur",
    realm: "Valinor",
    spouse: "Tulkas",
  },
  {
    birth: "YT, during the ,Noontide of Valinor",
    death: "Still alive",
    gender: "Female",
    hair: "Reddish brown",
    height: "",
    name: "Nerdanel",
    race: "Elves",
    realm: "",
    spouse: "Fëanor",
  },
  {
    birth: "",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Nellas",
    race: "Elves",
    realm: "",
    spouse: "None",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Nauglath",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Narvi",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "FA 503",
    gender: "Male",
    hair: "",
    height: "",
    name: "Naugladur",
    race: "Dwarves",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 1684",
    death: "TA 1856",
    gender: "Male",
    hair: "",
    height: "",
    name: "Narmacil II",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 1049",
    death: "TA 1294",
    gender: "Male",
    hair: "",
    height: "",
    name: "Narmacil I",
    race: "Men",
    realm: "Gondor",
    spouse: "Unknown, possibly none as he had no children",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Nahar",
    race: "Horse",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Mûmakil",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Early ,First Age",
    death: "FA 502",
    gender: "Male",
    hair: "",
    height: "",
    name: "Mîm",
    race: "Dwarves",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "March ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Muzgash",
    race: "Orc",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "YT 1170",
    gender: "Female",
    hair: "Silver",
    height: "",
    name: "Míriel",
    race: "Elves",
    realm: "",
    spouse: "Finwë",
  },
  {
    birth: "First Age",
    death: "Probably died on ,March 25TA 3019, during destruction of ,Mordor",
    gender: "Male",
    hair: "Most likely black or none",
    height: "6' 7\" (2.01 m)",
    name: "Mouth of Sauron",
    race: "Men",
    realm: "",
    spouse: "None",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "The Moth",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Perhaps ,Firstborn",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Morwë",
    race: "Elves",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late 26th century ,Third Age",
    death: "Late ,Third Age",
    gender: "Female",
    hair: "",
    height: "",
    name: "Morwen (Gondor)",
    race: "Men",
    realm: "",
    spouse: "Unnamed husband",
  },
  {
    birth: "FA 443",
    death: "FA 500",
    gender: "Female",
    hair: "Dark, grey in old age",
    height: "Tall",
    name: "Morwen",
    race: "Men",
    realm: "",
    spouse: "Húrin Thalion",
  },
  {
    birth: "",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Mithrellas",
    race: "Elves",
    realm: "",
    spouse: "Imrazôr",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Minastan",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 1454",
    death: "TA 1634",
    gender: "Male",
    hair: "",
    height: "",
    name: "Minardil",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "Mid ,Third Age",
    death: "July 13 ,1944",
    gender: "Male",
    hair: "",
    height: "",
    name: "Minohtar",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "SR 1381",
    death: "Early-,Fourth Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Merimas Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "YT",
    death: "Unknown, presumably still alive",
    gender: "Female",
    hair: "",
    height: "",
    name: "Meril-i-Turinqi",
    race: "Elves",
    realm: "Tol Eressëa",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Meneldor",
    race: "Eagles",
    realm: "",
    spouse: "",
  },
  {
    birth: "SA 3318",
    death: "TA 158",
    gender: "Male",
    hair: "",
    height: "",
    name: "Meneldil",
    race: "Men",
    realm: "Gondor",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Men",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "Immortal",
    gender: "Male",
    hair: "Dark",
    height: "Any size by choice",
    name: "Melkor",
    race: "Ainur",
    realm: "Utumno,Angband,Middle-earth,Beleriand",
    spouse: "",
  },
  {
    birth: "Before the creation of ,Arda",
    death:
      "Did not die being a ,Maia returned to ,Valinor, after the death of her husband Thingol",
    gender: "Female",
    hair: "Dark",
    height: "",
    name: "Melian",
    race: "Ainur",
    realm: "Doriath",
    spouse: "Thingol",
  },
  {
    birth: "Around FA 450 ",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Meleth",
    race: "Men",
    realm: "",
    spouse: "Agathor",
  },
  {
    birth: "3019",
    death: "February 29 ,3019",
    gender: "Male",
    hair: "Black (film)",
    height: "",
    name: "Mauhúr",
    race: "Uruk-hai",
    realm: "Isengard,Saruman",
    spouse: "none",
  },
  {
    birth: "TA 2890",
    death: "TA 2941",
    gender: "Male",
    hair: "Auburn (film)",
    height: "Tall (6'4\")",
    name: "Master of Laketown",
    race: "Men",
    realm: "Lake-town",
    spouse: "",
  },
  {
    birth: "SR 1182",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Marroc Brandybuck",
    race: "Hobbit",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "SR 1343",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Marmadas Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Mid-,Third Age",
    death: "Mid-Third Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Marhwini",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Mid ,Third Age",
    death: "TA 1856",
    gender: "Male",
    hair: "",
    height: "",
    name: "Marhari",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 1557",
    death: "Sometime after ,TA 1601",
    gender: "Male",
    hair: "",
    height: "",
    name: "Marcho",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 1960",
    death: "TA 2080",
    gender: "Male",
    hair: "",
    height: "",
    name: "Mardil Voronwë",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "FA 282",
    death: "FA 376",
    gender: "Male",
    hair: "",
    height: "",
    name: "Marach",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Before the Creation of Arda",
    death: "Immortal",
    gender: "Male",
    hair: "",
    height: "",
    name: "Manwë",
    race: "Ainur",
    realm: "Arda,Valinor",
    spouse: "Varda",
  },
  {
    birth: "After ,SA 61",
    death: "Early ,Second Age",
    gender: "Male",
    hair: "",
    height: "",
    name: "Manwendil",
    race: "Men",
    realm: "",
    spouse: "Possible unnamed wife",
  },
  {
    birth: "Late ,First Age",
    death: "Late First Age ",
    gender: "Male",
    hair: "",
    height: "",
    name: "Manthor",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Before the creation of Arda",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Mandos",
    race: "Ainur",
    realm: "",
    spouse: "Vairë",
  },
  {
    birth: "TA 2940",
    death: "TA 3015",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gálmód",
    race: "Men",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Unknown, possibly during the ,First Age",
    death: "FA 495",
    gender: "Male",
    hair: "Became grey in captivity",
    height: "",
    name: "Gwindor",
    race: "Elves",
    realm: "",
    spouse: "None, betrothed to ,Finduilas",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gwaihir",
    race: "Great Eagles",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "Blond",
    height: "",
    name: "Guthláf",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Mid ,First Age",
    death: "FA 456",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gundor",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Guilin",
    race: "Elves",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2563",
    death: "TA 2805",
    gender: "Male",
    hair: "",
    height: "",
    name: "Grór",
    race: "Dwarves",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "TA 2671",
    death: "TA 2923",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gróin",
    race: "Dwarves",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "Mid ,First Age",
    death: "FA 474",
    gender: "Male",
    hair: "",
    height: "",
    name: "Grithnir",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "February 29 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Grishnákh",
    race: "Orc",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "March 15 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Grimbold",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth:
      "Unknown, probably several years or so after the ,Battle of Five Armies",
    death: "Unknown, early ,Fourth Age",
    gender: "Male",
    hair: "Dark",
    height: "Tall (in Man-form)",
    name: "Grimbeorn",
    race: "Men,Skin-changer",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2862",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Rose Greenhand",
    race: "Hobbits",
    realm: "",
    spouse: "Cotman Cotton",
  },
  {
    birth: "TA 2810",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Holman Greenhand",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2859",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Hending Greenhand",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2851",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Halfred Greenhand",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2854",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Erling Greenhand",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "July ,2941",
    gender: "Male",
    hair: "Grey/white strands of hair (film)",
    height: "About nine feet (film)",
    name: "Great Goblin",
    race: "Orcs",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,First Age",
    death: "FA 460",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gorlim",
    race: "Men,Wraith",
    realm: "",
    spouse: "Eilinel",
  },
  {
    birth: "TA 2668",
    death: "TA 2741",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gram",
    race: "Men",
    realm: "Rohan",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "March 15, 3019 (film)",
    gender: "Male",
    hair: "white/gray, possibly light brown (film)",
    height: "5'9\" - 6'4\" (film)",
    name: "Gothmog (Lieutenant of Morgul)",
    race: "Orc",
    realm: "Minas Morgul,the Witch-King",
    spouse: "None",
  },
  {
    birth: "Before the creation of ,Arda",
    death: "FA 510",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gothmog",
    race: "Maiar,Balrogs",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gostir",
    race: "Dragons",
    realm: "",
    spouse: "",
  },
  {
    birth: "SR 1134",
    death: "SR 1236",
    gender: "Male",
    hair: "",
    height: "",
    name: 'Gormadoc "Deepdelver" Brandybuck',
    race: "Hobbits",
    realm: "Buckland",
    spouse: "Malva Headstrong",
  },
  {
    birth: "TA 2274",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gorhendad (Oldbuck) Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Gorgol",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2908",
    death: "Before ,TA 3001",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gorbulas Brandybuck",
    race: "Hobbits",
    realm: "",
    spouse: "Unnamed wife",
  },
  {
    birth: "",
    death: "March 14 ,3019, slain by ,Shagrat",
    gender: "Male",
    hair: "black",
    height: "medium",
    name: "Gorbag",
    race: "Uruk-hai,Orc",
    realm: "Cirith Ungol",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Bell (Goodchild) Gamgee",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Togo Goodbody",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Lily (Baggins) Goodbody",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "TA 2430",
    death: "March 25 ,3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Gollum",
    race: "Hobbits",
    realm: "",
    spouse: "",
  },
  {
    birth: "Unknown, before ,TA 2700",
    death: "TA 2747",
    gender: "Male",
    hair: "",
    height: "",
    name: "Golfimbul",
    race: "Orc,Goblin",
    realm: "Mount Gram",
    spouse: "None",
  },
  {
    birth: "",
    death: "",
    gender: "Female",
    hair: "",
    height: "",
    name: "Hanna (Goldworthy) Brandybuck",
    race: "Hobbit",
    realm: "",
    spouse: "Madoc Brandybuck",
  },
  {
    birth: "TA 2619",
    death: "TA 2699",
    gender: "Male",
    hair: "",
    height: "",
    name: "Goldwine",
    race: "Men",
    realm: "Rohan",
    spouse: "",
  },
  {
    birth: "",
    death: "",
    gender: "",
    hair: "",
    height: "",
    name: "Goldilocks (Gardner) Took",
    race: "",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "",
    gender: "Male",
    hair: "",
    height: "",
    name: "Golasgil",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "Late ,Third Age",
    death: "Presumably sometime after ,TA 3019",
    gender: "Male",
    hair: "",
    height: "",
    name: "Harry Goatleaf",
    race: "Men",
    realm: "",
    spouse: "",
  },
  {
    birth: "FA 415",
    death: "FA 473",
    gender: "Female",
    hair: "Blonde",
    height: "",
    name: "Glóredhel",
    race: "Men",
    realm: "",
    spouse: "Haldir",
  },
];
